/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedTosRouteImport } from './routes/_authenticated/tos'
import { Route as AuthenticatedSubscriptionRouteImport } from './routes/_authenticated/subscription'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPrivacyRouteImport } from './routes/_authenticated/privacy'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedFaqRouteImport } from './routes/_authenticated/faq'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as ApiNotificationsSendPushRouteImport } from './routes/api/notifications/send-push'
import { Route as ApiCronTrialExpiryRouteImport } from './routes/api/cron/trial-expiry'
import { Route as ApiCronFollowUpsRouteImport } from './routes/api/cron/follow-ups'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated/clients.$id'
import { Route as ApiDocumentsIdPdfRouteImport } from './routes/api/documents.$id.pdf'
import { Route as ApiPublicPortalTokenPdfRouteImport } from './routes/api/public/portal.$token.pdf'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTosRoute = AuthenticatedTosRouteImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubscriptionRoute =
  AuthenticatedSubscriptionRouteImport.update({
    id: '/subscription',
    path: '/subscription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrivacyRoute = AuthenticatedPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFaqRoute = AuthenticatedFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsSendPushRoute =
  ApiNotificationsSendPushRouteImport.update({
    id: '/api/notifications/send-push',
    path: '/api/notifications/send-push',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiCronTrialExpiryRoute = ApiCronTrialExpiryRouteImport.update({
  id: '/api/cron/trial-expiry',
  path: '/api/cron/trial-expiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronFollowUpsRoute = ApiCronFollowUpsRouteImport.update({
  id: '/api/cron/follow-ups',
  path: '/api/cron/follow-ups',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientsRoute,
} as any)
const ApiDocumentsIdPdfRoute = ApiDocumentsIdPdfRouteImport.update({
  id: '/api/documents/$id/pdf',
  path: '/api/documents/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalTokenPdfRoute = ApiPublicPortalTokenPdfRouteImport.update({
  id: '/api/public/portal/$token/pdf',
  path: '/api/public/portal/$token/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/faq': typeof AuthenticatedFaqRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tos': typeof AuthenticatedTosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/cron/follow-ups': typeof ApiCronFollowUpsRoute
  '/api/cron/trial-expiry': typeof ApiCronTrialExpiryRoute
  '/api/notifications/send-push': typeof ApiNotificationsSendPushRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/faq': typeof AuthenticatedFaqRoute
  '/pricing': typeof AuthenticatedPricingRoute
  '/privacy': typeof AuthenticatedPrivacyRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/subscription': typeof AuthenticatedSubscriptionRoute
  '/tos': typeof AuthenticatedTosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/cron/follow-ups': typeof ApiCronFollowUpsRoute
  '/api/cron/trial-expiry': typeof ApiCronTrialExpiryRoute
  '/api/notifications/send-push': typeof ApiNotificationsSendPushRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/faq': typeof AuthenticatedFaqRoute
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/privacy': typeof AuthenticatedPrivacyRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/subscription': typeof AuthenticatedSubscriptionRoute
  '/_authenticated/tos': typeof AuthenticatedTosRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/cron/follow-ups': typeof ApiCronFollowUpsRoute
  '/api/cron/trial-expiry': typeof ApiCronTrialExpiryRoute
  '/api/notifications/send-push': typeof ApiNotificationsSendPushRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/settings'
    | '/subscription'
    | '/tos'
    | '/portal/$token'
    | '/clients/$id'
    | '/documents/$id'
    | '/projects/$id'
    | '/api/cron/follow-ups'
    | '/api/cron/trial-expiry'
    | '/api/notifications/send-push'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/admin'
    | '/clients'
    | '/dashboard'
    | '/documents'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/projects'
    | '/settings'
    | '/subscription'
    | '/tos'
    | '/portal/$token'
    | '/clients/$id'
    | '/documents/$id'
    | '/projects/$id'
    | '/api/cron/follow-ups'
    | '/api/cron/trial-expiry'
    | '/api/notifications/send-push'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/admin'
    | '/_authenticated/clients'
    | '/_authenticated/dashboard'
    | '/_authenticated/documents'
    | '/_authenticated/faq'
    | '/_authenticated/pricing'
    | '/_authenticated/privacy'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/_authenticated/subscription'
    | '/_authenticated/tos'
    | '/portal/$token'
    | '/_authenticated/clients/$id'
    | '/_authenticated/documents/$id'
    | '/_authenticated/projects/$id'
    | '/api/cron/follow-ups'
    | '/api/cron/trial-expiry'
    | '/api/notifications/send-push'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
  PortalTokenRoute: typeof PortalTokenRoute
  ApiCronFollowUpsRoute: typeof ApiCronFollowUpsRoute
  ApiCronTrialExpiryRoute: typeof ApiCronTrialExpiryRoute
  ApiNotificationsSendPushRoute: typeof ApiNotificationsSendPushRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiDocumentsIdPdfRoute: typeof ApiDocumentsIdPdfRoute
  ApiPublicPortalTokenPdfRoute: typeof ApiPublicPortalTokenPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tos': {
      id: '/_authenticated/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof AuthenticatedTosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subscription': {
      id: '/_authenticated/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof AuthenticatedSubscriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/privacy': {
      id: '/_authenticated/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AuthenticatedPrivacyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faq': {
      id: '/_authenticated/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof AuthenticatedFaqRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/send-push': {
      id: '/api/notifications/send-push'
      path: '/api/notifications/send-push'
      fullPath: '/api/notifications/send-push'
      preLoaderRoute: typeof ApiNotificationsSendPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/trial-expiry': {
      id: '/api/cron/trial-expiry'
      path: '/api/cron/trial-expiry'
      fullPath: '/api/cron/trial-expiry'
      preLoaderRoute: typeof ApiCronTrialExpiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/follow-ups': {
      id: '/api/cron/follow-ups'
      path: '/api/cron/follow-ups'
      fullPath: '/api/cron/follow-ups'
      preLoaderRoute: typeof ApiCronFollowUpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/documents/$id/pdf': {
      id: '/api/documents/$id/pdf'
      path: '/api/documents/$id/pdf'
      fullPath: '/api/documents/$id/pdf'
      preLoaderRoute: typeof ApiDocumentsIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/$token/pdf': {
      id: '/api/public/portal/$token/pdf'
      path: '/api/public/portal/$token/pdf'
      fullPath: '/api/public/portal/$token/pdf'
      preLoaderRoute: typeof ApiPublicPortalTokenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedFaqRoute: typeof AuthenticatedFaqRoute
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedPrivacyRoute: typeof AuthenticatedPrivacyRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubscriptionRoute: typeof AuthenticatedSubscriptionRoute
  AuthenticatedTosRoute: typeof AuthenticatedTosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedFaqRoute: AuthenticatedFaqRoute,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedPrivacyRoute: AuthenticatedPrivacyRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubscriptionRoute: AuthenticatedSubscriptionRoute,
  AuthenticatedTosRoute: AuthenticatedTosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
  PortalTokenRoute: PortalTokenRoute,
  ApiCronFollowUpsRoute: ApiCronFollowUpsRoute,
  ApiCronTrialExpiryRoute: ApiCronTrialExpiryRoute,
  ApiNotificationsSendPushRoute: ApiNotificationsSendPushRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiDocumentsIdPdfRoute: ApiDocumentsIdPdfRoute,
  ApiPublicPortalTokenPdfRoute: ApiPublicPortalTokenPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
