/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as PortalTokenRouteImport } from './routes/portal.$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProjectsRouteImport } from './routes/_authenticated/projects'
import { Route as AuthenticatedPricingRouteImport } from './routes/_authenticated/pricing'
import { Route as AuthenticatedDocumentsRouteImport } from './routes/_authenticated/documents'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicGeoRouteImport } from './routes/api/public/geo'
import { Route as AuthenticatedProjectsIdRouteImport } from './routes/_authenticated/projects.$id'
import { Route as AuthenticatedDocumentsIdRouteImport } from './routes/_authenticated/documents.$id'
import { Route as ApiDocumentsIdPdfRouteImport } from './routes/api/documents.$id.pdf'
import { Route as ApiPublicPortalTokenPdfRouteImport } from './routes/api/public/portal.$token.pdf'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PortalTokenRoute = PortalTokenRouteImport.update({
  id: '/portal/$token',
  path: '/portal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjectsRoute = AuthenticatedProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPricingRoute = AuthenticatedPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentsRoute = AuthenticatedDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicGeoRoute = ApiPublicGeoRouteImport.update({
  id: '/api/public/geo',
  path: '/api/public/geo',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsIdRoute = AuthenticatedProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedProjectsRoute,
} as any)
const AuthenticatedDocumentsIdRoute =
  AuthenticatedDocumentsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedDocumentsRoute,
  } as any)
const ApiDocumentsIdPdfRoute = ApiDocumentsIdPdfRouteImport.update({
  id: '/api/documents/$id/pdf',
  path: '/api/documents/$id/pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPortalTokenPdfRoute = ApiPublicPortalTokenPdfRouteImport.update({
  id: '/api/public/portal/$token/pdf',
  path: '/api/public/portal/$token/pdf',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/pricing': typeof AuthenticatedPricingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/pricing': typeof AuthenticatedPricingRoute
  '/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/documents': typeof AuthenticatedDocumentsRouteWithChildren
  '/_authenticated/pricing': typeof AuthenticatedPricingRoute
  '/_authenticated/projects': typeof AuthenticatedProjectsRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/portal/$token': typeof PortalTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/documents/$id': typeof AuthenticatedDocumentsIdRoute
  '/_authenticated/projects/$id': typeof AuthenticatedProjectsIdRoute
  '/api/public/geo': typeof ApiPublicGeoRoute
  '/api/documents/$id/pdf': typeof ApiDocumentsIdPdfRoute
  '/api/public/portal/$token/pdf': typeof ApiPublicPortalTokenPdfRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/clients'
    | '/documents'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/portal/$token'
    | '/documents/$id'
    | '/projects/$id'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/clients'
    | '/documents'
    | '/pricing'
    | '/projects'
    | '/settings'
    | '/portal/$token'
    | '/'
    | '/documents/$id'
    | '/projects/$id'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/clients'
    | '/_authenticated/documents'
    | '/_authenticated/pricing'
    | '/_authenticated/projects'
    | '/_authenticated/settings'
    | '/portal/$token'
    | '/_authenticated/'
    | '/_authenticated/documents/$id'
    | '/_authenticated/projects/$id'
    | '/api/public/geo'
    | '/api/documents/$id/pdf'
    | '/api/public/portal/$token/pdf'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PortalTokenRoute: typeof PortalTokenRoute
  ApiPublicGeoRoute: typeof ApiPublicGeoRoute
  ApiDocumentsIdPdfRoute: typeof ApiDocumentsIdPdfRoute
  ApiPublicPortalTokenPdfRoute: typeof ApiPublicPortalTokenPdfRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/portal/$token': {
      id: '/portal/$token'
      path: '/portal/$token'
      fullPath: '/portal/$token'
      preLoaderRoute: typeof PortalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects': {
      id: '/_authenticated/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AuthenticatedProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pricing': {
      id: '/_authenticated/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof AuthenticatedPricingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documents': {
      id: '/_authenticated/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthenticatedDocumentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/geo': {
      id: '/api/public/geo'
      path: '/api/public/geo'
      fullPath: '/api/public/geo'
      preLoaderRoute: typeof ApiPublicGeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$id': {
      id: '/_authenticated/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof AuthenticatedProjectsIdRouteImport
      parentRoute: typeof AuthenticatedProjectsRoute
    }
    '/_authenticated/documents/$id': {
      id: '/_authenticated/documents/$id'
      path: '/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthenticatedDocumentsIdRouteImport
      parentRoute: typeof AuthenticatedDocumentsRoute
    }
    '/api/documents/$id/pdf': {
      id: '/api/documents/$id/pdf'
      path: '/api/documents/$id/pdf'
      fullPath: '/api/documents/$id/pdf'
      preLoaderRoute: typeof ApiDocumentsIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/portal/$token/pdf': {
      id: '/api/public/portal/$token/pdf'
      path: '/api/public/portal/$token/pdf'
      fullPath: '/api/public/portal/$token/pdf'
      preLoaderRoute: typeof ApiPublicPortalTokenPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedDocumentsRouteChildren {
  AuthenticatedDocumentsIdRoute: typeof AuthenticatedDocumentsIdRoute
}

const AuthenticatedDocumentsRouteChildren: AuthenticatedDocumentsRouteChildren =
  {
    AuthenticatedDocumentsIdRoute: AuthenticatedDocumentsIdRoute,
  }

const AuthenticatedDocumentsRouteWithChildren =
  AuthenticatedDocumentsRoute._addFileChildren(
    AuthenticatedDocumentsRouteChildren,
  )

interface AuthenticatedProjectsRouteChildren {
  AuthenticatedProjectsIdRoute: typeof AuthenticatedProjectsIdRoute
}

const AuthenticatedProjectsRouteChildren: AuthenticatedProjectsRouteChildren = {
  AuthenticatedProjectsIdRoute: AuthenticatedProjectsIdRoute,
}

const AuthenticatedProjectsRouteWithChildren =
  AuthenticatedProjectsRoute._addFileChildren(
    AuthenticatedProjectsRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedDocumentsRoute: typeof AuthenticatedDocumentsRouteWithChildren
  AuthenticatedPricingRoute: typeof AuthenticatedPricingRoute
  AuthenticatedProjectsRoute: typeof AuthenticatedProjectsRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedDocumentsRoute: AuthenticatedDocumentsRouteWithChildren,
  AuthenticatedPricingRoute: AuthenticatedPricingRoute,
  AuthenticatedProjectsRoute: AuthenticatedProjectsRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PortalTokenRoute: PortalTokenRoute,
  ApiPublicGeoRoute: ApiPublicGeoRoute,
  ApiDocumentsIdPdfRoute: ApiDocumentsIdPdfRoute,
  ApiPublicPortalTokenPdfRoute: ApiPublicPortalTokenPdfRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
